### ISSUE TITLE
There is no way to validate branch name with regex

### ISSUE THREAD

**Issue by iammuho** [mergeability/mergeable#438] opened 2020-12-14 15:05 UTC
Problem:

As a repo owner, I want to validate branches of the Pull-requests to have a format that is defined by regex.

Solution:

We need to have a `headRef` validator just as same as `baseRef`

**Comment by jusx** [comment] 2020-12-15 23:46
@shine2lay This is potentially a duplicate of #424 -- fyi

**Comment by shine2lay** [comment] 2020-12-16 00:37
duplicate of #424

**Closed by shine2lay** 2020-12-16 00:37 UTC
