### ISSUE TITLE
Allow to specify Group in required Reviewers

### ISSUE THREAD

**Issue by kolrami** [mergeability/mergeable#253] opened 2020-03-12 11:52 UTC
As far as I can see it is only possible at the moment to specify usernames in the `reviewers` setting of the `approvals` validator. Would it be possible to also allow Github groups there, i.e. check that at least on person out of a group as reviewed?

**Comment by shine2lay** [comment] 2020-04-01 03:02
Duplicate of #236

**Closed by shine2lay** 2020-04-01 03:02 UTC
Labels: ⏎ Duplicate
